version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: local_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1q2w3e4r!
      MYSQL_DATABASE: local_db
      MYSQL_USER: jhjh
      MYSQL_PASSWORD: jhjh12
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - "3306:3306"
