server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: false
    open-in-view: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
        globally_quoted_identifiers_skip_column_definitions: true
        format_sql: true
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
